package com.epayslip.interview.util;

import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

public class IdUtils {

	public static String getAutoGeneratedId(Object po) throws SecurityException, NoSuchMethodException {
		String autoGeneratedId = "";

		Field[] allFields = po.getClass().getDeclaredFields();

		for (Field f : allFields) {
			if (Modifier.isStatic(f.getModifiers())) {
				continue;
			}

			String getterName = "get" + ColnumNameUtils.capitalize(f.getName());
			Method getter = null;
			try {
				getter = po.getClass().getDeclaredMethod(getterName);
			} catch (NoSuchMethodException nme) {
				continue;
			}

			Id idAnno = getter.getAnnotation(Id.class);
			if (idAnno == null) {
				continue;
			}
			GeneratedValue generatedValueAnno = getter.getAnnotation(GeneratedValue.class);
			if (generatedValueAnno == null) {
				continue;
			} else {
				autoGeneratedId = f.getName();
				break;
			}

		}
		return autoGeneratedId;
	}

	public static void setAutoIncreamentIdValue(Object po, String autoGeneratedId, Object idValue) throws Exception, NoSuchMethodException {
		String setterName = "set" + ColnumNameUtils.capitalize(autoGeneratedId);
		Method setter = po.getClass().getDeclaredMethod(setterName, idValue.getClass());
		setter.invoke(po, idValue);
	}

}
